# Generated by Django 2.0.7 on 2018-07-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='id',
        ),
        migrations.AddField(
            model_name='developer',
            name='devID',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
