# Generated by Django 2.0.7 on 2018-07-28 13:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testApps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userTags', models.CharField(blank=True, max_length=1500, null=True)),
                ('deviceDetails', models.TextField(max_length=50000)),
                ('appUsedFirstOn', models.DateField(default=datetime.datetime(2018, 7, 28, 13, 42, 43, 729813))),
                ('applicationFinalReview', models.TextField(blank=True, default='', max_length=2500, null=True)),
                ('applicationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApps.testApp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
