# Generated by Django 2.0.7 on 2018-07-28 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180728_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='appUsedFirstOn',
            field=models.DateField(default=datetime.datetime(2018, 7, 28, 13, 45, 7, 575043)),
        ),
    ]
