# Generated by Django 2.0.7 on 2018-07-28 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180728_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='appUsedFirstOn',
            field=models.DateField(default=datetime.datetime(2018, 7, 28, 13, 47, 41, 936262, tzinfo=utc)),
        ),
    ]
