# Generated by Django 2.0.7 on 2018-07-28 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180728_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='appUsedFirstOn',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
