# Generated by Django 2.0.7 on 2018-07-28 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='testApp',
            fields=[
                ('applicationID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('applicationName', models.CharField(max_length=100)),
                ('applicationDescription', models.CharField(max_length=1000)),
                ('applicationDownloads', models.IntegerField(default=0)),
                ('applicationVerdict', models.TextField(default='')),
                ('applicationPartsToReview', models.TextField()),
                ('uploaderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.developer')),
            ],
        ),
    ]
