# Generated by Django 2.0.7 on 2018-07-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testapp',
            name='application',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
